"""V8 parity: the Python engine reproduces every fixture generated by the TS reference engine
(packages/shared/fixtures/engine.json) — same project JSON, same render manifest, same error codes — and every
command is exactly undoable."""

import json
from pathlib import Path

import pytest

from app.services import editor_engine as eng

FIXTURES = json.loads((Path(__file__).resolve().parents[3] / "packages/shared/fixtures/engine.json").read_text())


@pytest.mark.parametrize("f", FIXTURES, ids=[f["name"] for f in FIXTURES])
def test_fixture_parity(f):
    p = f["initial"]
    if f.get("error"):
        with pytest.raises(eng.EngineError) as e:
            for c in f["commands"]:
                p, _ = eng.apply(p, c)
        assert e.value.code == f["error"]
        return
    for c in f["commands"]:
        before = p
        p, inv = eng.apply(p, c)
        assert eng.apply_all(p, inv)[0] == before, c["type"]  # exact undo
    assert p == f["expected"]
    assert eng.render_manifest(p) == f["manifest"]


def test_subtitles_and_bool_is_not_an_int():
    f = next(x for x in FIXTURES if x["name"] == "text_audio_keyframes")
    m = eng.render_manifest(f["expected"])
    assert eng.to_srt(m["subtitles"]).startswith("1\n00:00:01,000 --> 00:00:04,000\nMerhaba dünya! Siktir git.\n")
    assert eng.to_vtt(m["subtitles"]).startswith("WEBVTT\n\n00:00:01.000 --> 00:00:04.000")
    with pytest.raises(eng.EngineError):
        eng.apply(f["expected"], {"type": "move_clip", "clip_id": "c2", "start_ms": True})
