"""Server port of the canonical command engine (packages/shared/src/engine.ts + manifest.ts), Master Spec V8 §6.

The server is authoritative: every client command is re-applied here. Behaviour must match the TS reference
exactly — `packages/shared/fixtures/engine.json` (generated by the TS engine) is replayed by the API tests, so a
divergence fails CI. Rules: integer milliseconds, half-up rounding, no overlaps on a track (except photo layers),
locked tracks/clips refuse edits, range checks; every command returns its inverse (undo)."""

from __future__ import annotations

import copy
import math
from typing import Any

DEFAULT_TRANSFORM = {"x": 0, "y": 0, "scale": 1, "rotation": 0, "opacity": 1}
DEFAULT_AUDIO = {"volume": 1, "fade_in_ms": 0, "fade_out_ms": 0, "muted": False}
KINDS = ("video", "audio", "text", "overlay", "effect")
PROPS = ("x", "y", "scale", "rotation", "opacity", "volume")
EASINGS = ("linear", "ease_in", "ease_out", "ease_in_out", "hold")
RANGES = {"x": (-100000, 100000), "y": (-100000, 100000), "scale": (0.01, 20), "rotation": (-360, 360),
          "opacity": (0, 1), "volume": (0, 4), "speed": (0.1, 8)}
PRESETS = {
    "vertical_1080": {"width": 1080, "height": 1920, "fps": 30, "background": "#000000"},
    "landscape_1080": {"width": 1920, "height": 1080, "fps": 30, "background": "#000000"},
    "square_1080": {"width": 1080, "height": 1080, "fps": 30, "background": "#000000"},
    "poster_a4": {"width": 1240, "height": 1754, "fps": 30, "background": "#ffffff"},
    "thumbnail": {"width": 1280, "height": 720, "fps": 30, "background": "#111111"},
}


class EngineError(Exception):
    def __init__(self, code: str, message: str | None = None):
        super().__init__(message or code)
        self.code = code


def round_half_up(x: float) -> int:
    return math.floor(x + 0.5)


def _fail(code: str, msg: str | None = None):
    raise EngineError(code, msg)


def _int(v: Any, name: str, lo: int = 0, hi: int = 86_400_000) -> int:
    if isinstance(v, bool) or not isinstance(v, (int, float)) or (isinstance(v, float) and not v.is_integer()):
        _fail("bad_value", f"{name} must be an integer in [{lo}, {hi}]")
    v = int(v)
    if v < lo or v > hi:
        _fail("bad_value", f"{name} must be an integer in [{lo}, {hi}]")
    return v


def _num(v: Any, name: str) -> float:
    lo, hi = RANGES.get(name, (-1e9, 1e9))
    if isinstance(v, bool) or not isinstance(v, (int, float)) or not math.isfinite(v) or v < lo or v > hi:
        _fail("bad_value", f"{name} out of range")
    return v


def _str(v: Any, name: str, mx: int = 200) -> str:
    if not isinstance(v, str) or len(v) == 0 or len(v) > mx:
        _fail("bad_value", f"{name} must be a string")
    return v


def new_project(project_id: str, type_: str, title: str, canvas: dict) -> dict:
    return {"schema": "cp1", "project_id": project_id, "type": type_, "title": title, "canvas": dict(canvas),
            "assets": {}, "tracks": [], "clips": {}, "dialogue_refs": [], "character_refs": [], "shot_graph": None}


def duration_ms(p: dict) -> int:
    return max([c["start_ms"] + c["duration_ms"] for c in p["clips"].values()] or [0])


def _track(p: dict, tid: Any) -> dict:
    for t in p["tracks"]:
        if t["id"] == tid:
            return t
    _fail("not_found", f"track {tid}")


def _clip(p: dict, cid: Any) -> dict:
    c = p["clips"].get(cid) if isinstance(cid, str) else None
    if c is None:
        _fail("not_found", f"clip {cid}")
    return c


def _editable(p: dict, c: dict) -> None:
    if c["locked"] or _track(p, c["track_id"])["locked"]:
        _fail("locked", "this layer is locked")


def _sort_track(p: dict, t: dict) -> None:
    t["clip_ids"].sort(key=lambda i: (p["clips"][i]["start_ms"], i))


def _check_overlap(p: dict, c: dict) -> None:
    if p["type"] == "photo":
        return
    for i in _track(p, c["track_id"])["clip_ids"]:
        if i == c["id"]:
            continue
        o = p["clips"][i]
        if c["start_ms"] < o["start_ms"] + o["duration_ms"] and o["start_ms"] < c["start_ms"] + c["duration_ms"]:
            _fail("overlap", f"overlaps {i}")


def _check_duration(p: dict, d: int) -> None:
    if p["type"] != "photo" and d <= 0:
        _fail("bad_value", "duration must be positive")


def _put_clip(p: dict, c: dict) -> None:
    prev = p["clips"].get(c["id"])
    if prev is not None and prev["track_id"] != c["track_id"]:
        old = _track(p, prev["track_id"])
        old["clip_ids"] = [x for x in old["clip_ids"] if x != c["id"]]
    p["clips"][c["id"]] = copy.deepcopy(c)
    t = _track(p, c["track_id"])
    if c["id"] not in t["clip_ids"]:
        t["clip_ids"].append(c["id"])
    _sort_track(p, t)


def _del_clip(p: dict, cid: str) -> None:
    c = _clip(p, cid)
    t = _track(p, c["track_id"])
    t["clip_ids"] = [x for x in t["clip_ids"] if x != cid]
    del p["clips"][cid]
    p["dialogue_refs"] = [r for r in p["dialogue_refs"] if r["clip_id"] != cid]


def _snap(c: dict) -> dict:
    return {"type": "put_clip", "clip": copy.deepcopy(c)}


def _primitive(p: dict, cmd: dict) -> bool:
    t = cmd.get("type")
    if t == "put_clip":
        _put_clip(p, cmd["clip"])
    elif t == "del_clip":
        _del_clip(p, cmd["clip_id"])
    elif t == "put_track":
        tr = copy.deepcopy(cmd["track"])
        p["tracks"] = [x for x in p["tracks"] if x["id"] != tr["id"]]
        p["tracks"].insert(min(cmd["index"], len(p["tracks"])), tr)
    elif t == "del_track":
        p["tracks"] = [x for x in p["tracks"] if x["id"] != cmd["track_id"]]
    elif t == "put_asset":
        p["assets"][cmd["asset"]["id"]] = copy.deepcopy(cmd["asset"])
    elif t == "del_asset":
        p["assets"].pop(cmd["asset_id"], None)
    elif t == "put_canvas":
        p["canvas"] = copy.deepcopy(cmd["canvas"])
    elif t == "put_title":
        p["title"] = cmd["title"]
    elif t == "put_refs":
        p["dialogue_refs"] = copy.deepcopy(cmd["dialogue_refs"])
        p["character_refs"] = copy.deepcopy(cmd["character_refs"])
    elif t == "put_shot_graph":
        p["shot_graph"] = copy.deepcopy(cmd["shot_graph"])
    else:
        return False
    return True


def _new_clip(p: dict, raw: dict) -> dict:
    raw = raw if isinstance(raw, dict) else {}
    cid = _str(raw.get("id"), "id", 80)
    if cid in p["clips"]:
        _fail("exists", f"clip {cid} exists")
    t = _track(p, raw.get("track_id"))
    asset = raw.get("asset_id")
    if asset is not None and asset not in p["assets"]:
        _fail("not_found", f"asset {asset}")
    if t["kind"] in ("video", "audio") and asset is None:
        _fail("bad_value", f"{t['kind']} clips need an asset")
    if t["kind"] == "audio" and p["assets"][asset]["kind"] not in ("audio", "video"):
        _fail("bad_value", "audio tracks take audio")
    c = {"id": cid, "track_id": t["id"], "asset_id": asset,
         "start_ms": _int(raw.get("start_ms", 0) if raw.get("start_ms") is not None else 0, "start_ms"),
         "duration_ms": _int(raw.get("duration_ms") if raw.get("duration_ms") is not None else 0, "duration_ms"),
         "in_ms": _int(raw.get("in_ms") if raw.get("in_ms") is not None else 0, "in_ms"),
         "speed": 1, "reverse": False, "transform": {**DEFAULT_TRANSFORM, **(raw.get("transform") or {})},
         "text": raw.get("text"), "shape": raw.get("shape"), "audio": dict(DEFAULT_AUDIO), "keyframes": {},
         "transition_in": {"type": "none", "ms": 0}, "effects": [], "group_id": None, "locked": False,
         "name": raw["name"][:80] if isinstance(raw.get("name"), str) else cid}
    if t["kind"] == "text" and c["text"] is None:
        _fail("bad_value", "text clips need text")
    if c["text"] is not None:
        text = {"font": "Inter", "size": 64, "color": "#ffffff", "align": "center", "weight": "bold"}
        text.update(c["text"])
        text["content"] = _str(c["text"].get("content"), "text", 2000)
        c["text"] = text
    for k in ("x", "y", "scale", "rotation", "opacity"):
        _num(c["transform"][k], k)
    _check_duration(p, c["duration_ms"])
    return c


def _shift_keyframes(k: dict, frm: int, length: int) -> dict:
    out = {}
    for prop in PROPS:
        lst = [{**x, "t_ms": x["t_ms"] - frm} for x in k.get(prop, []) if frm <= x["t_ms"] <= frm + length]
        if lst:
            out[prop] = lst
    return out


def _validate_shot_graph(g: Any) -> dict | None:
    if g is None:
        return None
    if not isinstance(g, dict):
        _fail("bad_value", "shot graph")
    _str(g.get("location"), "location", 120)
    ids: set = set()
    for key in ("actors", "cameras", "lights", "shots"):
        lst = g.get(key)
        if not isinstance(lst, list) or len(lst) > 50:
            _fail("bad_value", "shot graph lists")
        for x in lst:
            _str(x.get("id"), "id", 40)
            if x["id"] in ids:
                _fail("bad_value", f"duplicate id {x['id']}")
            ids.add(x["id"])
    for c in g["cameras"]:
        lens = c.get("lens_mm")
        if isinstance(lens, bool) or not isinstance(lens, (int, float)) or lens < 8 or lens > 300:
            _fail("bad_value", "lens_mm")
    cams = {c["id"] for c in g["cameras"]}
    for s in g["shots"]:
        if s.get("camera_id") not in cams:
            _fail("bad_value", f"shot {s['id']} uses an unknown camera")
        _int(s.get("duration_ms"), "duration_ms", 1000, 60000)
    return copy.deepcopy(g)


def apply(project: dict, cmd: dict) -> tuple[dict, list[dict]]:
    p = copy.deepcopy(project)
    inv: list[dict] = []
    if not isinstance(cmd, dict):
        _fail("unknown_command", str(cmd))
    if _primitive(p, cmd):
        return p, []
    t = cmd.get("type")
    if t == "set_title":
        inv.append({"type": "put_title", "title": p["title"]})
        p["title"] = _str(cmd.get("title"), "title", 120)
    elif t == "set_canvas":
        inv.append({"type": "put_canvas", "canvas": copy.deepcopy(p["canvas"])})
        c = dict(p["canvas"])
        if "width" in cmd:
            c["width"] = _int(cmd["width"], "width", 16, 7680)
        if "height" in cmd:
            c["height"] = _int(cmd["height"], "height", 16, 7680)
        if "fps" in cmd:
            c["fps"] = _int(cmd["fps"], "fps", 1, 120)
        if "background" in cmd:
            c["background"] = _str(cmd["background"], "background", 20)
        p["canvas"] = c
    elif t == "add_asset":
        a = cmd.get("asset") or {}
        _str(a.get("id"), "asset.id", 80)
        if a.get("kind") not in ("video", "image", "audio", "font"):
            _fail("bad_value", "asset kind")
        _str(a.get("uri"), "asset.uri", 500)
        inv.append({"type": "put_asset", "asset": copy.deepcopy(p["assets"][a["id"]])} if a["id"] in p["assets"]
                   else {"type": "del_asset", "asset_id": a["id"]})
        new = {"id": a["id"], "kind": a["kind"], "uri": a["uri"],
               "name": (a.get("name") if a.get("name") is not None else a["id"])[:120]}
        if "duration_ms" in a:
            new["duration_ms"] = _int(a["duration_ms"], "duration_ms")
        if "width" in a:
            new["width"] = _int(a["width"], "width", 1, 16384)
        if "height" in a:
            new["height"] = _int(a["height"], "height", 1, 16384)
        if a.get("license"):
            new["license"] = str(a["license"])[:200]
        p["assets"][a["id"]] = new
    elif t == "remove_asset":
        aid = cmd.get("asset_id")
        if aid not in p["assets"]:
            _fail("not_found", f"asset {aid}")
        if any(c["asset_id"] == aid for c in p["clips"].values()):
            _fail("in_use", "the asset is used by a clip")
        inv.append({"type": "put_asset", "asset": copy.deepcopy(p["assets"][aid])})
        del p["assets"][aid]
    elif t == "add_track":
        tid = _str(cmd.get("track_id"), "track_id", 80)
        if any(x["id"] == tid for x in p["tracks"]):
            _fail("exists", f"track {tid} exists")
        kind = cmd.get("kind")
        if kind not in KINDS:
            _fail("bad_value", "track kind")
        index = len(p["tracks"]) if cmd.get("index") is None else _int(cmd["index"], "index", 0, len(p["tracks"]))
        p["tracks"].insert(index, {"id": tid, "kind": kind,
                                   "name": cmd["name"][:60] if isinstance(cmd.get("name"), str) else kind,
                                   "clip_ids": [], "muted": False, "hidden": False, "locked": False})
        inv.append({"type": "del_track", "track_id": tid})
    elif t == "remove_track":
        tr = _track(p, cmd.get("track_id"))
        if tr["clip_ids"]:
            _fail("not_empty", "remove the clips first")
        inv.append({"type": "put_track", "track": copy.deepcopy(tr), "index": p["tracks"].index(tr)})
        p["tracks"] = [x for x in p["tracks"] if x["id"] != tr["id"]]
    elif t == "reorder_track":
        tr = _track(p, cmd.get("track_id"))
        frm = p["tracks"].index(tr)
        to = _int(cmd.get("index"), "index", 0, len(p["tracks"]) - 1)
        inv.append({"type": "reorder_track", "track_id": tr["id"], "index": frm})
        p["tracks"].pop(frm)
        p["tracks"].insert(to, tr)
    elif t == "set_track":
        tr = _track(p, cmd.get("track_id"))
        inv.append({"type": "put_track", "track": copy.deepcopy(tr), "index": p["tracks"].index(tr)})
        for k in ("muted", "hidden", "locked"):
            if isinstance(cmd.get(k), bool):
                tr[k] = cmd[k]
        if isinstance(cmd.get("name"), str):
            tr["name"] = cmd["name"][:60]
    elif t == "add_clip":
        c = _new_clip(p, cmd.get("clip"))
        if _track(p, c["track_id"])["locked"]:
            _fail("locked", "this track is locked")
        p["clips"][c["id"]] = c
        _track(p, c["track_id"])["clip_ids"].append(c["id"])
        _check_overlap(p, c)
        _sort_track(p, _track(p, c["track_id"]))
        inv.append({"type": "del_clip", "clip_id": c["id"]})
    elif t == "remove_clip":
        c = _clip(p, cmd.get("clip_id"))
        _editable(p, c)
        inv.append(_snap(c))
        if any(x["clip_id"] == c["id"] for x in p["dialogue_refs"]):
            inv.append({"type": "put_refs", "dialogue_refs": copy.deepcopy(p["dialogue_refs"]),
                        "character_refs": copy.deepcopy(p["character_refs"])})
        tr = _track(p, c["track_id"])
        later = [p["clips"][i] for i in tr["clip_ids"]
                 if p["clips"][i]["start_ms"] >= c["start_ms"] + c["duration_ms"]] if cmd.get("ripple") is True else []
        _del_clip(p, c["id"])
        for o in later:
            if o["locked"]:
                _fail("locked", "a later clip is locked")
            inv.append(_snap(o))
            o["start_ms"] -= c["duration_ms"]
        _sort_track(p, tr)
    elif t == "move_clip":
        c = _clip(p, cmd.get("clip_id"))
        _editable(p, c)
        inv.append(_snap(c))
        to = _track(p, cmd["track_id"]) if cmd.get("track_id") is not None else _track(p, c["track_id"])
        if to["locked"]:
            _fail("locked", "the target track is locked")
        frm = _track(p, c["track_id"])
        visual = ("video", "overlay")
        if to["kind"] != frm["kind"] and not (to["kind"] in visual and frm["kind"] in visual):
            _fail("bad_value", f"can't move a {frm['kind']} clip to a {to['kind']} track")
        moved = {**c, "start_ms": _int(cmd.get("start_ms"), "start_ms"), "track_id": to["id"]}
        _put_clip(p, moved)
        _check_overlap(p, p["clips"][c["id"]])
    elif t == "trim_clip":
        c = _clip(p, cmd.get("clip_id"))
        _editable(p, c)
        inv.append(_snap(c))
        delta = _int(cmd.get("delta_ms"), "delta_ms", -86_400_000)
        side = cmd.get("side")
        if side == "start":
            src = round_half_up(delta * c["speed"])
            if c["in_ms"] + src < 0:
                _fail("bad_value", "trim before the start of the media")
            c["start_ms"] += delta
            c["in_ms"] += src
            c["duration_ms"] -= delta
            if c["start_ms"] < 0:
                _fail("bad_value", "start before 0")
        elif side == "end":
            c["duration_ms"] += delta
        else:
            _fail("bad_value", "side must be start or end")
        _check_duration(p, c["duration_ms"])
        if c["duration_ms"] < 0:
            _fail("bad_value", "negative duration")
        a = p["assets"].get(c["asset_id"]) if c["asset_id"] else None
        if a is not None and a.get("duration_ms") is not None and a["kind"] != "image" and \
                c["in_ms"] + round_half_up(c["duration_ms"] * c["speed"]) > a["duration_ms"]:
            _fail("bad_value", "trim beyond the end of the media")
        _sort_track(p, _track(p, c["track_id"]))
        _check_overlap(p, c)
    elif t == "split_clip":
        c = _clip(p, cmd.get("clip_id"))
        _editable(p, c)
        at = _int(cmd.get("at_ms"), "at_ms")
        if at <= c["start_ms"] or at >= c["start_ms"] + c["duration_ms"]:
            _fail("bad_value", "split point must be inside the clip")
        nid = _str(cmd.get("new_clip_id"), "new_clip_id", 80)
        if nid in p["clips"]:
            _fail("exists", f"clip {nid} exists")
        inv.extend([{"type": "del_clip", "clip_id": nid}, _snap(c)])
        first = at - c["start_ms"]
        right = {**copy.deepcopy(c), "id": nid, "start_ms": at, "duration_ms": c["duration_ms"] - first,
                 "in_ms": c["in_ms"] + round_half_up(first * c["speed"]), "transition_in": {"type": "none", "ms": 0},
                 "keyframes": _shift_keyframes(c["keyframes"], first, c["duration_ms"] - first),
                 "name": f"{c['name']} (2)"}
        c["keyframes"] = _shift_keyframes(c["keyframes"], 0, first)
        c["duration_ms"] = first
        _put_clip(p, c)
        _put_clip(p, right)
    elif t == "slip_clip":
        c = _clip(p, cmd.get("clip_id"))
        _editable(p, c)
        inv.append(_snap(c))
        c["in_ms"] = _int(cmd.get("in_ms"), "in_ms")
        a = p["assets"].get(c["asset_id"]) if c["asset_id"] else None
        if a is not None and a.get("duration_ms") is not None and \
                c["in_ms"] + round_half_up(c["duration_ms"] * c["speed"]) > a["duration_ms"]:
            _fail("bad_value", "slip beyond the media")
    elif t == "set_clip":
        c = _clip(p, cmd.get("clip_id"))
        if not (c["locked"] and all(k in ("type", "clip_id", "locked") for k in cmd)):
            _editable(p, c)
        inv.append(_snap(c))
        if cmd.get("transform") is not None:
            tf = {**c["transform"], **cmd["transform"]}
            for k in ("x", "y", "scale", "rotation", "opacity"):
                _num(tf[k], k)
            c["transform"] = tf
        if cmd.get("text") is not None:
            if c["text"] is None:
                _fail("bad_value", "not a text clip")
            c["text"] = {**c["text"], **cmd["text"]}
            _str(c["text"].get("content"), "text", 2000)
            _int(c["text"].get("size"), "size", 4, 1000)
        if cmd.get("shape") is not None:
            if c["shape"] is None:
                _fail("bad_value", "not a shape clip")
            c["shape"] = {**c["shape"], **cmd["shape"]}
        if cmd.get("audio") is not None:
            au = {**c["audio"], **cmd["audio"]}
            _num(au["volume"], "volume")
            _int(au["fade_in_ms"], "fade_in_ms")
            _int(au["fade_out_ms"], "fade_out_ms")
            c["audio"] = au
        if "speed" in cmd:
            s = _num(cmd["speed"], "speed")
            c["duration_ms"] = round_half_up((c["duration_ms"] * c["speed"]) / s)
            c["speed"] = s
            _check_duration(p, c["duration_ms"])
            _check_overlap(p, c)
        if isinstance(cmd.get("reverse"), bool):
            c["reverse"] = cmd["reverse"]
        if isinstance(cmd.get("locked"), bool):
            c["locked"] = cmd["locked"]
        if isinstance(cmd.get("name"), str):
            c["name"] = cmd["name"][:80]
        if isinstance(cmd.get("effects"), list):
            c["effects"] = copy.deepcopy(cmd["effects"])[:20]
    elif t == "set_keyframe":
        c = _clip(p, cmd.get("clip_id"))
        _editable(p, c)
        prop = cmd.get("prop")
        if prop not in PROPS:
            _fail("bad_value", "keyframe property")
        easing = cmd.get("easing") if cmd.get("easing") is not None else "linear"
        if easing not in EASINGS:
            _fail("bad_value", "easing")
        tt = _int(cmd.get("t_ms"), "t_ms", 0, c["duration_ms"])
        inv.append(_snap(c))
        kf = {"t_ms": tt, "value": _num(cmd.get("value"), prop), "easing": easing}
        lst = [k for k in c["keyframes"].get(prop, []) if k["t_ms"] != tt]
        lst.append(kf)
        lst.sort(key=lambda k: k["t_ms"])
        c["keyframes"] = {**c["keyframes"], prop: lst}
    elif t == "remove_keyframe":
        c = _clip(p, cmd.get("clip_id"))
        _editable(p, c)
        prop = cmd.get("prop")
        lst = c["keyframes"].get(prop, [])
        if not any(k["t_ms"] == cmd.get("t_ms") for k in lst):
            _fail("not_found", "keyframe")
        inv.append(_snap(c))
        rest = [k for k in lst if k["t_ms"] != cmd.get("t_ms")]
        nxt = dict(c["keyframes"])
        if rest:
            nxt[prop] = rest
        else:
            nxt.pop(prop, None)
        c["keyframes"] = nxt
    elif t == "set_transition":
        c = _clip(p, cmd.get("clip_id"))
        _editable(p, c)
        if cmd.get("transition") not in ("none", "fade", "dissolve"):
            _fail("bad_value", "transition")
        inv.append(_snap(c))
        c["transition_in"] = {"type": cmd["transition"],
                              "ms": _int(cmd.get("ms") if cmd.get("ms") is not None else 0, "ms", 0,
                                         max(0, c["duration_ms"]))}
    elif t == "group":
        gid = _str(cmd.get("group_id"), "group_id", 80)
        ids = cmd.get("clip_ids")
        if not isinstance(ids, list) or len(ids) < 2:
            _fail("bad_value", "group needs 2+ clips")
        for i in ids:
            c = _clip(p, i)
            inv.append(_snap(c))
            c["group_id"] = gid
    elif t == "ungroup":
        for c in p["clips"].values():
            if c["group_id"] == cmd.get("group_id"):
                inv.append(_snap(c))
                c["group_id"] = None
    elif t == "link_dialogue":
        r = cmd.get("ref") or {}
        _clip(p, r.get("clip_id"))
        inv.append({"type": "put_refs", "dialogue_refs": copy.deepcopy(p["dialogue_refs"]),
                    "character_refs": copy.deepcopy(p["character_refs"])})
        p["dialogue_refs"] = [x for x in p["dialogue_refs"] if x["clip_id"] != r["clip_id"]] + [
            {"clip_id": r["clip_id"], "production_id": _str(r.get("production_id"), "production_id", 80),
             "episode": _int(r.get("episode"), "episode", 1, 10000), "line_id": _str(r.get("line_id"), "line_id", 40)}]
    elif t == "set_character_refs":
        inv.append({"type": "put_refs", "dialogue_refs": copy.deepcopy(p["dialogue_refs"]),
                    "character_refs": copy.deepcopy(p["character_refs"])})
        p["character_refs"] = copy.deepcopy(cmd.get("refs") or [])[:50]
    elif t == "set_shot_graph":
        inv.append({"type": "put_shot_graph", "shot_graph": copy.deepcopy(p["shot_graph"])})
        p["shot_graph"] = _validate_shot_graph(cmd.get("shot_graph"))
    else:
        _fail("unknown_command", str(t))
    inv.reverse()
    return p, inv


def apply_all(project: dict, cmds: list[dict]) -> tuple[dict, list[dict]]:
    p, inverse = project, []
    for c in cmds:
        p, inv = apply(p, c)
        inverse = inv + inverse
    return p, inverse


def touches(cmd: dict) -> set[str]:
    out = set()
    for k in ("clip_id", "track_id", "asset_id", "new_clip_id", "group_id"):
        if isinstance(cmd.get(k), str):
            out.add(f"{k.replace('new_', '')}:{cmd[k]}")
    c = cmd.get("clip")
    if isinstance(c, dict) and c.get("id"):
        out.add(f"clip_id:{c['id']}")
    if isinstance(cmd.get("clip_ids"), list):
        out |= {f"clip_id:{i}" for i in cmd["clip_ids"]}
    t = cmd.get("type")
    if t in ("set_canvas", "put_canvas"):
        out.add("canvas")
    if t in ("set_title", "put_title"):
        out.add("title")
    if t in ("set_shot_graph", "put_shot_graph"):
        out.add("shot_graph")
    if t in ("link_dialogue", "set_character_refs", "put_refs"):
        out.add("refs")
    if t in ("add_track", "remove_track", "reorder_track", "put_track", "del_track"):
        out.add("track_order")
    return out


# ---------------------------------------------------------------- render manifest (rm1)

def render_manifest(p: dict) -> dict:
    layers, audio, subs = [], [], []
    for z, t in enumerate(p["tracks"]):
        for cid in t["clip_ids"]:
            c = p["clips"][cid]
            a = p["assets"].get(c["asset_id"]) if c["asset_id"] else None
            end = c["start_ms"] + c["duration_ms"]
            if (t["kind"] == "audio" or (t["kind"] == "video" and a is not None and a["kind"] == "video")) and \
                    a is not None and not t["muted"] and not c["audio"]["muted"]:
                audio.append({"clip_id": c["id"], "asset": {"id": a["id"], "uri": a["uri"]}, "start_ms": c["start_ms"],
                              "end_ms": end, "in_ms": c["in_ms"], "speed": c["speed"], "volume": c["audio"]["volume"],
                              "fade_in_ms": c["audio"]["fade_in_ms"], "fade_out_ms": c["audio"]["fade_out_ms"],
                              "keyframes": {"volume": c["keyframes"]["volume"]}
                              if c["keyframes"].get("volume") else {}})
            if t["kind"] == "audio" or t["hidden"]:
                continue
            if t["kind"] == "text" and c["text"] is not None:
                subs.append({"start_ms": c["start_ms"], "end_ms": end, "text": c["text"]["content"]})
            kind = "text" if c["text"] is not None else "shape" if c["shape"] is not None else (
                "video" if a is not None and a["kind"] == "video" else "image")
            layers.append({"clip_id": c["id"], "z": z, "kind": kind,
                           "asset": {"id": a["id"], "kind": a["kind"], "uri": a["uri"]} if a else None,
                           "start_ms": c["start_ms"], "end_ms": end, "in_ms": c["in_ms"], "speed": c["speed"],
                           "reverse": c["reverse"], "transform": c["transform"], "keyframes": c["keyframes"],
                           "text": c["text"], "shape": c["shape"], "transition_in": c["transition_in"],
                           "effects": c["effects"]})
    subs.sort(key=lambda s: (s["start_ms"], s["end_ms"]))
    return {"schema": "rm1", "project_id": p["project_id"], "type": p["type"], "canvas": p["canvas"],
            "duration_ms": duration_ms(p), "layers": layers, "audio": audio, "subtitles": subs}


def _ts(ms: int, sep: str) -> str:
    return f"{ms // 3_600_000:02d}:{ms % 3_600_000 // 60_000:02d}:{ms % 60_000 // 1000:02d}{sep}{ms % 1000:03d}"


def to_srt(subs: list[dict]) -> str:
    return "\n".join(f"{i + 1}\n{_ts(s['start_ms'], ',')} --> {_ts(s['end_ms'], ',')}\n{s['text']}\n"
                     for i, s in enumerate(subs))


def to_vtt(subs: list[dict]) -> str:
    return "WEBVTT\n\n" + "\n".join(f"{_ts(s['start_ms'], '.')} --> {_ts(s['end_ms'], '.')}\n{s['text']}\n"
                                     for s in subs)
