"""AI Studio assembly (CPU, ffmpeg): normalize shots, fade transitions, captions (WebVTT sidecar, optional
burn-in), licensed music bed with loudness normalization, then the standard final encode (watermark/provenance).
Shot audio (e.g. generated by the provider) is kept and the music is mixed under it."""

from __future__ import annotations

import subprocess
from pathlib import Path

from ..audio.core import has_audio


def _run(cmd: list[str]) -> None:
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"ffmpeg failed: {r.stderr[-400:]}")


def _ts(ms: int) -> str:
    h, rem = divmod(int(ms), 3_600_000)
    m, rem = divmod(rem, 60_000)
    s, ms_ = divmod(rem, 1000)
    return f"{h:02d}:{m:02d}:{s:02d}.{ms_:03d}"


def write_vtt(captions: list[dict], path: Path) -> Path:
    lines = ["WEBVTT", ""]
    for i, c in enumerate(captions, 1):
        text = str(c["text"]).replace("-->", "→").strip()
        lines += [str(i), f"{_ts(c['start_ms'])} --> {_ts(c['end_ms'])}", text, ""]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def normalize(src: Path, dst: Path, w: int, h: int, dur_s: float, fade: bool, fps: int = 24,
              start_s: float = 0.0) -> Path:
    vf = f"scale={w}:{h}:force_original_aspect_ratio=increase,crop={w}:{h},fps={fps},format=yuv420p"
    if fade:
        vf += ",fade=t=in:st=0:d=0.4"
    if has_audio(src):
        audio_in, amap = [], ["-map", "0:a:0"]
    else:
        audio_in, amap = ["-f", "lavfi", "-i", "anullsrc=r=48000:cl=stereo"], ["-map", "1:a:0"]
    seek = ["-ss", f"{start_s:.3f}"] if start_s else []  # trims cut the existing render (no re-generation)
    _run(["ffmpeg", "-y", "-loglevel", "error", *seek, "-i", str(src), *audio_in, "-t", f"{dur_s:.3f}", "-vf", vf,
          "-map", "0:v:0", *amap, "-c:v", "libx264", "-preset", "veryfast", "-crf", "20", "-c:a", "aac",
          "-ar", "48000", "-ac", "2", "-shortest", str(dst)])
    return dst


def assemble(shots: list[tuple[Path, dict]], spec: dict, workdir: Path, music: Path | None) -> tuple[Path, Path | None]:
    w, h = (int(x) for x in spec["resolution"].split("x"))
    parts = []
    for i, (path, s) in enumerate(shots):
        parts.append(normalize(path, workdir / f"n{i:02d}.mp4", w, h, s["duration_ms"] / 1000,
                               fade=s.get("transition") == "fade" and i > 0,
                               start_s=s.get("trim_start_ms", 0) / 1000))
    lst = workdir / "concat.txt"
    lst.write_text("".join(f"file '{p.name}'\n" for p in parts))
    joined = workdir / "joined.mp4"
    _run(["ffmpeg", "-y", "-loglevel", "error", "-f", "concat", "-safe", "0", "-i", str(lst), "-c", "copy",
          str(joined)])
    vtt = write_vtt(spec["captions"], workdir / "captions.vtt") if spec.get("captions") else None
    current = joined
    if vtt is not None and spec.get("burn_in"):
        burned = workdir / "burned.mp4"
        _run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(current), "-vf",
              f"subtitles={vtt}:force_style='Fontsize=14,Outline=1'", "-c:a", "copy", str(burned)])
        current = burned
    if music is not None and has_audio(music):
        vol = float((spec.get("audio") or {}).get("music_volume", 0.25))
        total = sum(s["duration_ms"] for _, s in shots) / 1000
        mixed = workdir / "mixed.mp4"
        _run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(current), "-stream_loop", "-1", "-i", str(music),
              "-filter_complex",
              f"[1:a]volume={vol},afade=t=out:st={max(0.0, total - 1.0):.2f}:d=1[m];"
              f"[0:a][m]amix=inputs=2:duration=first:dropout_transition=0,loudnorm=I=-14:TP=-1.5:LRA=11[a]",
              "-map", "0:v:0", "-map", "[a]", "-c:v", "copy", "-c:a", "aac", "-b:a", "160k", "-t", f"{total:.3f}",
              str(mixed)])
        current = mixed
    return current, vtt
