"""multi person

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 22:06:50.040574
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=False),
    sa.Column('declared_size', sa.BigInteger(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending_upload', 'analyzing', 'ready', 'rejected', 'failed', 'deleted', name='source_video_status'), nullable=False),
    sa.Column('rights_attested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attestation_version', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('analysis_job_id', sa.UUID(), nullable=True),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rejection_reason', sa.String(length=120), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_source_videos_user_id'), 'source_videos', ['user_id'], unique=False)
    op.create_table('video_persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_video_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('first_frame', sa.Integer(), nullable=False),
    sa.Column('last_frame', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('face_visible_ratio', sa.Float(), nullable=False),
    sa.Column('median_face_px', sa.Integer(), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=512), nullable=True),
    sa.Column('selectable', sa.Boolean(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_video_id', 'track_id', name='uq_video_persons_track')
    )
    op.create_index(op.f('ix_video_persons_source_video_id'), 'video_persons', ['source_video_id'], unique=False)
    op.create_table('job_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['identity_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'track_id', name='uq_job_assignments_track')
    )
    op.create_index(op.f('ix_job_assignments_job_id'), 'job_assignments', ['job_id'], unique=False)
    job_kind = postgresql.ENUM('template', 'analysis', 'multi_replace', name='job_kind')
    job_kind.create(op.get_bind(), checkfirst=True)
    op.add_column('generation_jobs', sa.Column('kind', postgresql.ENUM(name='job_kind', create_type=False),
                                               nullable=False, server_default='template'))
    op.add_column('generation_jobs', sa.Column('source_video_id', sa.UUID(), nullable=True))
    op.add_column('generation_jobs', sa.Column('preferred_model', sa.String(length=60), nullable=True))
    op.add_column('generation_jobs', sa.Column('fallback_model', sa.String(length=60), nullable=True))
    op.add_column('generation_jobs', sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False,
                                               server_default=sa.text("'{}'::jsonb")))
    # Backfill the model-routing snapshot for existing template jobs.
    op.execute("""UPDATE generation_jobs j SET preferred_model = v.preferred_model, fallback_model = v.fallback_model
                  FROM template_versions v WHERE v.id = j.template_version_id""")
    op.execute("UPDATE generation_jobs SET preferred_model = 'unknown' WHERE preferred_model IS NULL")
    op.alter_column('generation_jobs', 'preferred_model', nullable=False)
    op.alter_column('generation_jobs', 'template_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('generation_jobs', 'template_version_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_generation_jobs_source_video_id'), 'generation_jobs', ['source_video_id'], unique=False)
    op.create_foreign_key('fk_jobs_source_video', 'generation_jobs', 'source_videos', ['source_video_id'], ['id'],
                          ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Non-template jobs cannot satisfy the old NOT NULL template columns.
    op.execute("DELETE FROM generation_jobs WHERE kind <> 'template'")
    op.drop_constraint('fk_jobs_source_video', 'generation_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_generation_jobs_source_video_id'), table_name='generation_jobs')
    op.alter_column('generation_jobs', 'template_version_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('generation_jobs', 'template_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('generation_jobs', 'spec')
    op.drop_column('generation_jobs', 'fallback_model')
    op.drop_column('generation_jobs', 'preferred_model')
    op.drop_column('generation_jobs', 'source_video_id')
    op.drop_column('generation_jobs', 'kind')
    op.drop_index(op.f('ix_job_assignments_job_id'), table_name='job_assignments')
    op.drop_table('job_assignments')
    op.drop_index(op.f('ix_video_persons_source_video_id'), table_name='video_persons')
    op.drop_table('video_persons')
    op.drop_index(op.f('ix_source_videos_user_id'), table_name='source_videos')
    op.drop_table('source_videos')
    op.execute('DROP TYPE IF EXISTS job_kind')
    op.execute('DROP TYPE IF EXISTS source_video_status')
    # ### end Alembic commands ###
